### ISSUE TITLE
"asdf-make: Failed to GPG verification"

### ISSUE THREAD

**Issue by takeshiyagiuchi** [yacchi/asdf-make#13]
**Describe the bug**
An error is thrown when trying to install make v4.3

**Steps to reproduce**
```
asdf plugin add make
asdf install make 4.3

* Downloading make release 4.3...
asdf-make: Failed to GPG verification
```

**Expected behavior**
make 4.3 is installed

**Screenshots**

**Additional context**
Running on Mac

**Comment by yacchi** [comment]
If `use-keyboxd` in `gnupg` conf (`~/.gnupg/common.conf`) is enabled, you will need to add the signature manually.

Please check the README for instructions on how to do this.
https://github.com/yacchi/asdf-make#import-gpg-public-key
